import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/Sidebar";
import Footer from "@/app/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({children, hasBg}) {

  return (
    <html lang="hy">
    <body className={'bg-black'}>
    <div className={`flex`}>
      <Sidebar/>
      <main className="flex-1">{children}</main>
    </div>
    </body>
    </html>
  );
}
